WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
SIDEBAR_WIDTH = 200
HUD_HEIGHT = 40
TILE_SIZE = 16
GRID_ROWS = (WINDOW_HEIGHT - HUD_HEIGHT) // TILE_SIZE
GRID_COLS = (WINDOW_WIDTH - SIDEBAR_WIDTH) // TILE_SIZE





FPS = 60
